### ISSUE TITLE
`riot foo/bar baz.js` does not handle symlinks in foo/bar

### ISSUE THREAD

**Issue by juodumas** [riot/cli#14]
`riot foo/bar baz.js` does not handle symlinks in `foo/bar` because  `shelljs.find()` does not dive into symlinked directories ( https://github.com/riot/cli/blob/master/lib/helpers.js#L20). It would be nice if it did.

**Comment by GianlucaGuarini** [comment]
I will update shelljs on the next release hoping they have fixed this issue that is not riot specific. Thanks for pointing this out

**Comment by juodumas** [comment]
Just checked, it's working with shelljs@0.7.0 and currently you have
0.6.0.

Took a look at their repo, looks like they have some breaking changes:
https://github.com/shelljs/shelljs/wiki/Migrating-from-v0.6-to-v0.7


Thanks.

**Comment by GianlucaGuarini** [comment]
fixed in `riot-cli@2.5.0` thanks for reporting it
