### ISSUE TITLE
 Css preprocessor was not found. Have you installed it locally?"

### ISSUE THREAD

**Issue by jaysalvat** [riot/cli#15]
Hello! :)

Sorry for my question. Sure I'm missing something simple.

**The --style flag doesn't seem to work for me. --type and --template are ok.** 

I've installed all the parsers:

    $ npm install babel jade coffee-script node-sass less

And tried all the flags;

    $ riot src dist --type coffeescript

Works.

    $ riot src dist --type babel

Works.

    $ riot src dist --template jade

Works.

But...

    $ riot src dist --style sass

_"The "sass" css preprocessor was not found. Have you installed it locally?"_

    $ riot src dist --style less

_"The "less" css preprocessor was not found. Have you installed it locally?"_

I also tried:

    $ riot src dist --type lessc

_"The "lessc" javascript preprocessor was not found. Have you installed it locally?"_

    $ riot src dist --type node-sass

_"The "node-sass" javascript preprocessor was not found. Have you installed it locally?"_

What am I missing?

Thanks in advance.

**Comment by GianlucaGuarini** [comment]
Hi have you tried to install the dependencies using the `-g` flag?

**Comment by jaysalvat** [comment]
Thanks @GianlucaGuarini ! It works with -g.

The message said "Have you installed it locally?". Not Globally.

Thanks :)

**Comment by GianlucaGuarini** [comment]
It depends where you run `$ riot`, if you have it installed globally you need to install your dependencies globally, if you run it via npm inside a project a project folder your require calls will be resolved locally

**Comment by jaysalvat** [comment]
Makes sens. Thanks for your time !
