### ISSUE TITLE
Ubuntu watch issue

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/cli#22]
see https://github.com/riot/riot/issues/2043

**Comment by drorhilman** [comment]
I figured out some new behavior:
I am running the server and the riot-compiler on a linux machine, and the .tag files
are on a shared mounted disk between the linux and windows machine.
Now, when I am editing and saving the files FROM WINDOWS - then the watching is not working.
However, when I am editing the files on the LINUX machine, it work fine.

Why can't riot-compiler listen to file change when it works from windows? Is there a way to fix this behavior (and do the development on windows)

**Comment by GianlucaGuarini** [comment]
duplicate of https://github.com/riot/riot/issues/1979 ?

**Comment by GianlucaGuarini** [comment]
closed due to inactivity
