### ISSUE TITLE
In 6.x, the babel package has been deprecated in favor of babel-cli

### ISSUE THREAD

**Issue by chrisdothtml** [riot/cli#28]
Keep getting this warning when installing `riot`. From what I can tell, looks like `babel` (now `babel-cli`) should be a `devDependency` of this package anyway.

> riot > riot-cli > babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers

**Comment by GianlucaGuarini** [comment]
thanks fixed in riot-cli@3.0.4
