### ISSUE TITLE
Is this cli planned to be compatible with Riot@4?

### ISSUE THREAD

**Issue by nibushibu** [riot/cli#35]
I used this cli when I want to precompile Riot tags without using bundler such as webpack.

Will this cli be maintained even after version 4?

**Comment by GianlucaGuarini** [comment]
Of course, I have it on my TODO list. I just need to find time for it 😄

**Comment by nibushibu** [comment]
Thank you for your reply!
I patiently wait. ☕️🍵

**Comment by GianlucaGuarini** [comment]
the new @riotjs/cli alpha is out
