### ISSUE TITLE
Failed to compile multiple riot components to a single js file

### ISSUE THREAD

**Issue by infuzz** [riot/cli#37]
Hello, seems that options to compile all riot tags in a dir to a single concatenated file is not present/not supported in V4  ?
Options was : 
riot foo/bar baz.js    To a single concatenated file (baz.js)

when I try to use :
riot foo/bar baz.js
=> console shows each file .riot compiling to baz.js   as expected
But when I have a look on output file baz.js it contains randomely some compiled tags, but not all.

**Comment by kiichi** [comment]
probably, cache option in rollup will help? I just played with src/compile.js and src/index.js.

https://rollupjs.org/guide/en/#advanced-functionality

I hope this help:

in src/compile.js

```
let cache;
```
then inside compile function, just before return, returned the rollup object without write statement

```
cache = bundle.cache;
return bundle;//.write(options.output)
```

Then, in src/index.js where main() resolve all Promise objects, I tried to verbose all compiled code from the cache like below, and it's kind works. I just not sure how to export & register with proper tag name. 

```
return await Promise.all(options._.map(input => generateOutput(options, input))).then(bundle=>{
			const allCode = bundle[0].map(bnd=>{
				const obj = bnd.cache.modules[0];
				const code = obj.code.substr(0, obj.code.length - 1).replace('export default ', '');
				const name = 'not-found';//obj.meta.tagName; // not sure how to get this
				return "riot.register('" + name + "'," + code + ");";
			}).join('\n\n');
			console.log(allCode);
		});
```

I tested like this

```
node index.js ~/my-project-dir/tags -o dist/one.js --extension html
```
of course dist/one.js doesn't have compiled code anymore, instead, the console shows all combined code

**Comment by GianlucaGuarini** [comment]
The new Riot.js CLI doesn't concat the components in one single javascript file since it doesn't make sense with the new API. You can either compile your whole [application via cli](https://riot.js.org/compiler/#build-your-whole-application) or compile all your **single** tags into **single** javascript output files [check here](https://riot.js.org/compiler/#compilation-via-riotjs-cli)

**Comment by infuzz** [comment]
Yes I successfully compile each single file into single javascript file. But I'm not sure to understand why it doen't make sense to have  only one file. Sorry for that (maybe a stupid question). It's not fun to include dozen of pre compiled script with <script>  tag. 
Anyway, until I set up all to compile as a whole app with cli, as you suggested and as a temporary solution, at this time I use the funny @kiichi [compile_me tag](https://github.com/kiichi/riotjs4-examples/tree/master/tags) to get only one js file that build a single file with compiled tag && auto register fct.

**Comment by GianlucaGuarini** [comment]
closing this issue because it's not actually an issue
