### ISSUE TITLE
cli ralways eturns exitcode 0 on errors

### ISSUE THREAD

**Issue by agreif** [riot/cli#39]
1. Describe your issue:

compiling .riot file on the commandline returns always 0, even on errors.
This happens in the following cases:

for a nonexistent file:

    $ ~/node_modules/.bin/riot none-xistent-file.riot
    (node:25239) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'none-xistent-file'
    at statSync (fs.js:915:3)
    ...

    $ echo $?
    0

and also if the file exists but has no root node:

    $ touch foo.riot
    $ ~/node_modules/.bin/riot foo.riot 
    (node:25366) UnhandledPromiseRejectionWarning: Error: [1,0]: Root tag not found.
    ...

    $ echo $?
    0

Wishful bugfix: in case of an error, a not-zeroexitcode should be returned in the shell, so that the calling process can recognize the error

2. Can you reproduce the issue?

  yes, install riot cli v 4.0.3 ad do the steps in 1)

4. Which version of Riot does it affect?

    $ ~/node_modules/.bin/riot -v
    4.0.3

5. How would you tag this issue?

  - [ ] Question
  - [ X] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by GianlucaGuarini** [comment]
Feature added in @riotjs/cli@5.1.1
