### ISSUE TITLE
Does cli support typescript syntax in `<script>` tag?

### ISSUE THREAD

**Issue by nibushibu** [riot/cli#48]
It seems that cli does not yet support typescript compilation as shown in the examples accompanying the following release.
(I apologize if I'm wrong.)

https://github.com/riot/riot/releases/tag/v5.4.0

Are there any plans to make it possible to compile typescript in cli in the future?

**Comment by GianlucaGuarini** [comment]
Fixed in v5.2.0. Thank you for reporting it

**Comment by GianlucaGuarini** [comment]
It seems that the new compiler version + rollup have still problem with this feature, I am on it

**Comment by pranoveraj** [comment]
new compiler already exists in JS (Visual Studio Code)

**Comment by GianlucaGuarini** [comment]
this feature was added in https://github.com/riot/cli/releases/tag/v5.3.0

**Comment by nibushibu** [comment]
Thank you!!!
I'm very grateful for your quick response. 🚀
