### ISSUE TITLE
Upgrading from v5 to v6

### ISSUE THREAD

**Issue by matteobruni** [riot/cli#51]
## Help us to manage our issues by answering the following:

1. Describe your issue:

After upgrading from v5 to v6 I got an error with the build config.

I had a config with `export default`, but changing it with `module.exports` the error has disappeared.

Another error is still occurring:

```
Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work
```

And I don't know how to fix it.

The previous error before this told me to install the package `@babel/preset-typescript`.

2. Can you reproduce the issue?

The issue can be seen [here](https://github.com/matteobruni/tsparticles/tree/dev/components/riot)

To see the error run:

```
yarn && npx lerna bootstrap && npx lerna run build
```

3. On which browser/OS does the issue appear?

macOS

4. Which version of Riot does it affect?

v6

5. How would you tag this issue?

  - [x] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by GianlucaGuarini** [comment]
Fixed in v6.0.5
