### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by gregorypratt** [riot/cli#6]
I get this error with v2.3.0 of the riot npm package...

<img width="464" alt="screen shot 2015-11-06 at 09 30 19" src="https://cloud.githubusercontent.com/assets/1453899/10993739/09b6ad90-8469-11e5-8549-b7c9823459ab.png">

**Comment by GianlucaGuarini** [comment]
Are you using node 4.0.0?

**Comment by gregorypratt** [comment]
I was using 0.12.6, I'll switch to 4.0.0 and build again, or should I go to 5.0.0?

**Comment by GianlucaGuarini** [comment]
Any version [>=4.0.0](https://github.com/riot/cli/blob/master/package.json#L7) should be good

**Comment by gregorypratt** [comment]
Upped to v5 and it worked :+1: 

Thanks!
